user_facture:
    path:     /facture
    defaults: { _controller: UserBundle:User:factures }

user_facturePDF:
    path:     /facturepdf/{id}
    defaults: { _controller: UserBundle:User:facturesPDF }