produits:
    type: rest
    resource: "@EcommerceFrontRestBundle/Controller/ProduitController.php"
    name_prefix:  api_
    options:
        expose: true

categories:
    type: rest
    resource: "@EcommerceFrontRestBundle/Controller/CategorieController.php"
    name_prefix:  api_
    options:
        expose: true


admin_rest:
    type: annotation
    resource: "@EcommerceFrontRestBundle/Controller/AdminController.php"
    prefix: /