parameters:
    base_handler.class: BaseHandler

    produit_name: produit
    produit_entity.class: Ecommerce\EcommerceBundle\Entity\Produit
    produit_manager.class: Ecommerce\EcommerceBundle\Services\ProduitManager
    produit_repository: EcommerceBundle:Produit
    produit_type.class: Ecommerce\EcommerceBundle\Form\Type\ProduitType
    produit_handler.class: Ecommerce\EcommerceBundle\Form\Handler\ProduitHandler


    categorie_name: categorie
    categorie_entity.class: Ecommerce\EcommerceBundle\Entity\Categorie
    categorie_manager.class: Ecommerce\EcommerceBundle\Services\CategorieManager
    categorie_repository: EcommerceBundle:Categorie
    categorie_type.class: Ecommerce\EcommerceBundle\Form\Type\CategorieType
    categorie_handler.class: Ecommerce\EcommerceBundle\Form\Handler\CategorieHandler

    tva_extension.class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension

