ecommerce_panier:
    resource: "@EcommerceBundle/Resources/config/routing/panier_routing.yml"
    prefix:   /panier

ecommerce_produit:
    resource: "@EcommerceBundle/Resources/config/routing/produit_routing.yml"
    prefix:   /produit

ecommerce_categorie:
    resource: "@EcommerceBundle/Resources/config/routing/categorie_routing.yml"
    prefix:   /categorie
