parameters:
    produit_name: produit
    produit_type.class: Ecommerce\EcommerceBundle\Form\Type\ProduitType
    produit_entity.class: Ecommerce\EcommerceBundle\Entity\Produit
    produit_handler.class: Ecommerce\EcommerceBundle\Form\Handler\ProduitHandler
    produit_manager.class: Ecommerce\EcommerceBundle\Services\ProduitManager
    produit_repository.class: Ecommerce\EcommerceBundle\Repository\ProduitRepository
    base_handler.class: BaseHandler

services:
    ecommerce_manager:
        abstract: true
        factory: ["@doctrine.orm.entity_manager", getRepository]

    produit_manager:
        class: "%produit_manager.class%"
        arguments: ['@doctrine.orm.entity_manager']

    base_form:
        class: Form
        abstract: true
        factory: ["@form.factory", createNamed]

    produit_form:
        parent: base_form
        arguments:
            - "%produit_name%"
            - "%produit_type.class%"
            - "@produit_entity"

    produit_entity:
        class: "%produit_entity.class%"

    base_handler:
        abstract: true
        calls:
            - [setRequest, ['@request_stack']]
            - [setSecurity, ['@security.token_storage']]

    produit_handler:
        class: "%produit_handler.class%"
        parent: base_handler
        arguments: ["@produit_form", "@produit_manager"]



