imports:
    - { resource: parameters.yml }

services:
services:
    ecommerce_manager:
        abstract: true
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setRepository, [EcommerceBundle:Categorie]]

    produit_manager:
        class: "%produit_manager.class%"
        parent: ecommerce_manager
        calls:
            - [setRepository, ["%produit_repository%"]]

    categorie_manager:
        class: "%categorie_manager.class%"
        parent: ecommerce_manager
        calls:
            - [setRepository, ["%categorie_repository%"]]

    base_form:
        class: Form
        abstract: true
        factory: ["@form.factory", createNamed]

    base_handler:
        abstract: true
        calls:
            - [setRequest, ['@request_stack']]
            - [setSecurity, ['@security.token_storage']]

    produit_form:
        parent: base_form
        arguments:
            - "%produit_name%"
            - "%produit_type.class%"
            - "@produit_entity"

    produit_entity:
        class: "%produit_entity.class%"

    produit_handler:
        class: "%produit_handler.class%"
        parent: base_handler
        arguments: ["@produit_form", "@produit_manager"]

    categorie_form:
        parent: base_form
        arguments:
            - "%categorie_name%"
            - "%categorie_type.class%"
            - "@categorie_entity"

    categorie_entity:
        class: "%produit_entity.class%"

    categorie_handler:
        class: "%categorie_handler.class%"
        parent: base_handler
        arguments: ["@categorie_form", "@categorie_manager"]



