#AsseticBundle configuration & filtres (jsqueeze, scssphp)
#assetic:
#    debug:          '%kernel.debug%'
#    use_controller: '%kernel.debug%'
#    filters:
#        scssphp:
#            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
#        jsqueeze: ~

# Twig Configuration
