liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        produitThumb:
            quality: 80
            filters:
                thumbnail: { size: [300, 150], mode: inset }
        produit:
            quality: 75
            filters:
                thumbnail: { size: [470, 300], mode: outbound }
