# Utilisation des CORS pour permettre certains navigateurs d'accpeter les requêtes AJAX
nelmio_cors:
    paths:
      '^/api':
          allow_origin: ['*']
          allow_headers: ['x-requested-with']
          allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
          max_age: 3600