# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    #encryption: "%mailer_encryption%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
