imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: bundles/twig.yml }
    - { resource: bundles/doctrine.yml}
    - { resource: bundles/swiftmailer.yml}
    - { resource: bundles/knp_paginator.yml}
    - { resource: bundles/fos_user.yml}
    - { resource: bundles/sonata.yml}
    - { resource: bundles/liip_imagine.yml}
    - { resource: "@EcommerceFrontBundle/Resources/config/services.yml" }
    - { resource: "@PagesBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@EcommerceBackBundle/Resources/config/services.yml" }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    admin_mailer: bobodiallobe@gmail.com

framework:
    #esi:             ~
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~






