imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_api.yml"
    serializer:
        enabled: true

# Serialisation des entites
jms_serializer:
    metadata:
        directories:
            EcommerceRest:
                namespace_prefix: Ecommerce\FrontBundle\Entity
                path: "@EcommerceFrontRestBundle/Resources/config/serializer"

## FostRestBundle
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

# nelmio
nelmio_api_doc: ~