imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
         main:
             http_basic:

# base de données de test
# Note: Pour utiliser l'orm test en ligne de commande pas besoin de préciser
# l'option --em=test, --env=test seulement suffit:
# exemple: php bin/console doctrine:schema:create --env=test
doctrine:
    dbal:
        driver: pdo_mysql
        host: localhost
        user: root
        password: bdiallo
        dbname: testecommerce
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            test:
                mappings: ~

