imports:
    - { resource: config.yml }
    - { resource: bundles/jms_serializer.yml }
    - { resource: bundles/fos_rest.yml }
    - { resource: bundles/nelmio_api_doc.yml }
    - { resource: bundles/nelmio_cors.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_api.yml"
    serializer:
        enabled: true

