back_commande:
    path:  /
    defaults: { _controller: "EcommerceBackBundle:Commande:commandes" }
    methods:  GET

back_commande_show:
    path:  /{id}/facture
    defaults: { _controller: "EcommerceBackBundle:Commande:showFacture" }
    methods: GET