back_produits:
    path:  /
    defaults: { _controller: "EcommerceBackBundle:Produit:index" }
    methods:  GET

back_produits_show:
    path:  /{id}/show
    defaults: { _controller: "EcommerceBackBundle:Produit:show" }
    methods: GET

back_produits_create:
    path:  /create
    defaults: { _controller: "EcommerceBackBundle:Produit:create" }
    methods:  [GET, POST]


back_produits_update:
    path:  /{id}/update
    defaults: { _controller: "EcommerceBackBundle:Produit:update" }
    methods:  [GET, POST, PUT]

back_produits_delete:
    path:  /{id}/delete
    defaults: { _controller: "EcommerceBackBundle:Produit:delete" }
    methods:  [DELETE, POST]

back_media_create:
    path:  /media/create
    defaults: { _controller: "EcommerceBackBundle:Produit:createMedia" }
