page_show:
    path:     /show/{slug}
    defaults: { _controller: PagesBundle:Pages:show }

page_menu:
    path:     /menu
    defaults: { _controller: PagesBundle:Pages:menu }

page_all:
    path:     /pages
    defaults: { _controller: PagesBundle:Pages:pages }

page_create:
    path:     /create
    defaults: { _controller: PagesBundle:Pages:create }
