Ecommerce\FrontBundle\Entity\Categorie:
    exclusion_policy: all
    properties:
        id:
            expose: true
        name:
            expose: true

    relations:
        -
            rel: self
            href: "expr('/app_api.php/api/categories/' ~ object.getId())"
        -
            rel: produits
            href: "expr('/app_api.php/api/categories/' ~ object.getId() ~ '/produits')"