Ecommerce\FrontBundle\Entity\Produit:
    exclusion_policy: all
    properties:
        id:
            expose: true
        name:
            expose: true
        price:
            expose: true
        description:
            expose: true
        image:
            expose: true
        categorie:
            expose: true

    relations:
        -
            rel: self
            href: "expr('/app_api.php/api/produits/' ~ object.getId())"
        -
            rel: categorie
            href: "expr('/app_api.php/api/categories/' ~ object.getCategorie().getId())"
#            href:
#                route: api_get_produits
#                parameters:
#                    id: "expr(object.getId())"
