panier_index:
    path:     /
    defaults: { _controller: EcommerceBundle:Panier:panier }

panier_livraison:
    path:     /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

panier_validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }

panier_ajouter_produit:
    path:     /ajouter/{id}
    defaults: { _controller: EcommerceBundle:Panier:ajouterProduit}

panier_supprimer_produit:
    path:     /supprimer/{id}
    defaults: { _controller: EcommerceBundle:Panier:supprimerProduit}