produit_produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produit:produits }

produit_presentation:
    path:     /presentation/{id}
    defaults: { _controller: EcommerceBundle:Produit:presentation }

produit_recherche:
    path:     /traiterRecherche/
    defaults: { _controller: EcommerceBundle:Produit:traiterRecherche }