ecommerce_back_produit:
    resource: "@EcommerceBackBundle/Resources/config/routing/produit_routing.yml"
    prefix:     /admin/produit

ecommerce_back_categorie:
    resource: "@EcommerceBackBundle/Resources/config/routing/categorie_routing.yml"
    prefix:     /admin/categorie

ecommerce_back_commande:
    resource: "@EcommerceBackBundle/Resources/config/routing/commande_routing.yml"
    prefix:     /admin/commande