services:

    ecommerce_mailer:
        class: Ecommerce\BackBundle\Services\Mailer
        arguments: ['@mailer', '@templating', '%admin_mailer%']

    ecommerce_mailer_listener:
        class: Ecommerce\BackBundle\Services\MailerListener
        arguments: ['@ecommerce_mailer', "@commande_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: process }

    ################ SonataAdminBundle ####################
    admin.category:
        class: Ecommerce\BackBundle\Admin\CategorieAdmin
        arguments: [~, Ecommerce\FrontBundle\Entity\Categorie, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Categorie }

    admin.produit:
        class: Ecommerce\BackBundle\Admin\ProduitAdmin
        arguments: [~, Ecommerce\FrontBundle\Entity\Produit, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Produit }