services:

    ecommerce_mailer:
        class: Ecommerce\BackBundle\Services\Mailer
        arguments: ['@mailer', '@templating', '%admin_mailer%']

    ecommerce_mailer_listener:
        class: Ecommerce\BackBundle\Services\MailerListener
        arguments: ['@ecommerce_mailer', "@commande_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: process }

    ###################### SonataAdminBundle ########################

    # Configuration admin list

    # produit
    admin.produit:
        class: Ecommerce\BackBundle\Admin\ProduitAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Produit"
        arguments: [~, Ecommerce\FrontBundle\Entity\Produit, ~]

    # categorie
    admin.categorie:
        class: Ecommerce\BackBundle\Admin\CategorieAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Categorie"
        arguments: [~, Ecommerce\FrontBundle\Entity\Categorie, ~]

    # client
    admin.client:
        class: Ecommerce\BackBundle\Admin\ClientAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Client"
        arguments: [~, Ecommerce\FrontBundle\Entity\Client, ~]

    # tva
    admin.tva:
        class: Ecommerce\BackBundle\Admin\TvaAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Tva"
        arguments: [~, Ecommerce\FrontBundle\Entity\Tva, ~ ]

    # commande
    admin.commande:
        class: Ecommerce\BackBundle\Admin\CommandeAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Commande"
        arguments: [~, Ecommerce\FrontBundle\Entity\Commande, ~ ]