services:
    base_form:
        class: Form
        abstract: true
        factory: ["@form.factory", createNamed]

    base_handler:
        abstract: true
        calls:
            - [setContainer, ['@service_container']]

    produit_form:
        parent: base_form
        arguments:
            - "%produit_name%"
            - "%produit_type.class%"
            - "@produit_entity"

    produit_entity:
        class: "%produit_entity.class%"

    produit_handler:
        class: "%produit_handler.class%"
        parent: base_handler
        arguments: ["@produit_form", "@produit_manager", "%produit_type.class%"]

    categorie_form:
        parent: base_form
        arguments:
            - "%categorie_name%"
            - "%categorie_type.class%"
            - "@categorie_entity"

    categorie_entity:
        class: "%produit_entity.class%"

    categorie_handler:
        class: "%categorie_handler.class%"
        parent: base_handler
        arguments: ["@categorie_form", "@categorie_manager", "%categorie_type.class%"]


    client_form:
        parent: base_form
        arguments:
            - "%client_name%"
            - "%client_type.class%"
            - "@client_entity"

    client_entity:
        class: "%client_entity.class%"

    client_handler:
        class: "%client_handler.class%"
        parent: base_handler
        arguments: ["@client_form", "@client_manager", "%client_type.class%"]

    commande_form:
        parent: base_form
        arguments:
            - "%commande_name%"
            - "%commande_type.class%"
            - "@commande_entity"

    commande_entity:
        class: "%commande_entity.class%"

    commande_handler:
        class: "%commande_handler.class%"
        parent: base_handler
        arguments: ["@commande_form", "@commande_manager", "%commande_type.class%"]
