services:
    redirect_listener:
        class: "%redirection_listener.class%"
        arguments: ['@service_container']
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

