pages_adminPages:
    resource: "@PagesBundle/Resources/config/routing/admin_pages.yml"
    prefix:   /admin/pages

pages:
    resource: "@PagesBundle/Resources/config/routing/pages_routing.yml"
    prefix:   /pages

