imports:
    - { resource: services/parameters.yml }
    - { resource: services/managers_services.yml }
    - { resource: services/formHandler_services.yml }
    - { resource: services/twigExtensions_services.yml }
    - { resource: services/listeners_services.yml }
    - { resource: services/facture_services.yml }

services:
    panier_session:
        class: "%panier.class%"
        arguments:
            ['@request_stack', '@session']

    ecommerce_pagination:
        class: Ecommerce\FrontBundle\Services\Pagination
        arguments: ['@knp_paginator', '@request_stack']







