<?php

namespace Pages\PagesBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRemove()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.deletedAt IS NOT NULL');

        return $qb->getQuery()->getResult();
    }
}

