produit_produits:
    path:     /
    defaults: { _controller: EcommerceFrontBundle:Produit:produits }

produit_presentation:
    path:     /presentation/{id}
    defaults: { _controller: EcommerceFrontBundle:Produit:presentation }

produit_recherche:
    path:     /traiterRecherche/
    defaults: { _controller: EcommerceFrontBundle:Produit:traiterRecherche }


produit_testjson:
    path:     /json/
    defaults: { _controller: EcommerceFrontBundle:Produit:json }

