<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function recherche($name)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.name like :name')
            ->andWhere('p.available = 1')
            ->orderBy('p.name')
            ->setParameter('name', $name)
            ->getQuery()
        ;

        return $query->getResult();
    }
}
